In [12]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [71]:
data = pd.read_csv("data/movie_metadata.csv")
data.head(4)

,movie_title,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Avatar,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000.0
1,Pirates of the Caribbean: At World's End,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0.0
2,Spectre,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000.0
3,The Dark Knight Rises,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000.0

<h2>Top 5 Directors with most movies directed</h2>

In [16]:
cols = ['movie_title','director_name']
data[cols]

                                            movie_title      director_name
0                                               Avatar       James Cameron
1             Pirates of the Caribbean: At World's End      Gore Verbinski
2                                              Spectre          Sam Mendes
3                                The Dark Knight Rises   Christopher Nolan
4     Star Wars: Episode VII - The Force Awakens    ...        Doug Walker
...                                                 ...                ...
5039                         The Following                             NaN
5040                              A Plague So Pleasant    Benjamin Roberds
5041                                  Shanghai Calling         Daniel Hsia
5042                                 My Date with Drew            Jon Gunn
5043                                Starting Over Again     Olivia Lamasan

[5044 rows x 2 columns]

In [17]:
movies_per_director = data.groupby("director_name").size()
movies_per_director

director_name
A. Raven Cruz         1
Aaron Hann            1
Aaron Schneider       1
Aaron Seltzer         1
Abel Ferrara          1
                     ..
Zoran Lisinac         1
Álex de la Iglesia    1
Émile Gaudreault      1
Éric Tessier          1
Étienne Faure         1
Length: 2399, dtype: int64

In [21]:
top5_by_director = movies_per_director.sort_values(ascending = False)
top5_by_director[:5]

director_name
Steven Spielberg    26
Woody Allen         22
Clint Eastwood      20
Martin Scorsese     20
Ridley Scott        17
dtype: int64

<h2>Top 5 Directors ranked based on the total gross incomes from all the movies they directed</h2>

In [36]:
cols = ['gross', 'movie_title', 'director_name']
data[cols]

,gross,movie_title,director_name
0,760505847.0,Avatar,James Cameron
1,309404152.0,Pirates of the Caribbean: At World's End,Gore Verbinski
2,200074175.0,Spectre,Sam Mendes
3,448130642.0,The Dark Knight Rises,Christopher Nolan
4,NaN,Star Wars: Episode VII - The Force Awakens ...,Doug Walker
...,...,...,...
5039,NaN,The Following,NaN
5040,NaN,A Plague So Pleasant,Benjamin Roberds
5041,10443.0,Shanghai Calling,Daniel Hsia
5042,85222.0,My Date with Drew,Jon Gunn
5043,NaN,Starting Over Again,Olivia Lamasan

In [38]:
gross_per_director = data.groupby("director_name")['gross'].sum()
gross_per_director

director_name
A. Raven Cruz                0.0
Aaron Hann                   0.0
Aaron Schneider        9176553.0
Aaron Seltzer         48546578.0
Abel Ferrara           1227324.0
                         ...
Zoran Lisinac                0.0
Álex de la Iglesia        3607.0
Émile Gaudreault       6239558.0
Éric Tessier                 0.0
Étienne Faure                0.0
Name: gross, Length: 2399, dtype: float64

In [39]:
top5_by_gross = gross_per_director.sort_values(ascending = False)
top5_by_gross[:5]

director_name
Steven Spielberg    4.114233e+09
Peter Jackson       2.592969e+09
Michael Bay         2.231243e+09
Tim Burton          2.071275e+09
Sam Raimi           2.049549e+09
Name: gross, dtype: float64

<h2>Genre(s) of Movie(s) directed by Lamasan and was released in the Philippines</h2>

In [51]:
data.head(5)
cols = ['country', 'movie_title', 'genres', 'director_name']
data[cols]

,country,movie_title,genres,director_name
0,USA,Avatar,Action|Adventure|Fantasy|Sci-Fi,James Cameron
1,USA,Pirates of the Caribbean: At World's End,Action|Adventure|Fantasy,Gore Verbinski
2,UK,Spectre,Action|Adventure|Thriller,Sam Mendes
3,USA,The Dark Knight Rises,Action|Thriller,Christopher Nolan
4,NaN,Star Wars: Episode VII - The Force Awakens ...,Documentary,Doug Walker
...,...,...,...,...
5039,USA,The Following,Crime|Drama|Mystery|Thriller,NaN
5040,USA,A Plague So Pleasant,Drama|Horror|Thriller,Benjamin Roberds
5041,USA,Shanghai Calling,Comedy|Drama|Romance,Daniel Hsia
5042,USA,My Date with Drew,Documentary,Jon Gunn
5043,Philippines,Starting Over Again,Romance|Comedy|Filipino,Olivia Lamasan

In [70]:
cond = (data['director_name'].str.contains('Lamasan', na=False) & (data['country'] == 'Philippines'))
data[cond][['movie_title', 'genres']]

              movie_title                   genres
5043  Starting Over Again  Romance|Comedy|Filipino

<h2>How many movies has a movie duration between 150 and 180</h2>

In [72]:
data.columns

Index(['movie_title', 'color', 'director_name', 'num_critic_for_reviews',
       'duration', 'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [73]:
cols = ['duration', 'movie_title']
data[cols]

      duration                                        movie_title
0        178.0                                            Avatar
1        169.0          Pirates of the Caribbean: At World's End
2        148.0                                           Spectre
3        164.0                             The Dark Knight Rises
4          NaN  Star Wars: Episode VII - The Force Awakens    ...
...        ...                                                ...
5039      43.0                         The Following
5040      76.0                              A Plague So Pleasant
5041     100.0                                  Shanghai Calling
5042      90.0                                 My Date with Drew
5043       NaN                                Starting Over Again

[5044 rows x 2 columns]

In [82]:
cond = data['duration'].between(150,180)
movies = data[cond]
total_movies = movies.shape[0]
total_movies

157

<h2>Which country has the most number of movies with duration between 150 and 180</h2>

In [92]:
cols = ['country', 'movie_title']
movies[cols]

     country                                movie_title
0        USA                                    Avatar
1        USA  Pirates of the Caribbean: At World's End
3        USA                     The Dark Knight Rises
6        USA                              Spider-Man 3
9         UK    Harry Potter and the Half-Blood Prince
...      ...                                        ...
4528   India        Rocket Singh: Salesman of the Year
4572   India                                      Fiza
4593   India              Chocolate: Deep Dark Secrets
4688     USA                               Hoop Dreams
4885     USA                            The Big Parade

[157 rows x 2 columns]

In [102]:
country = movies[cols].groupby('country').size().sort_values(ascending=False)
country[:1]

country
USA    111
dtype: int64